# For full config options, check the docs:
#    docs.serverless.com

# NOTE: most of the values here are coming from the appropriate settings.yaml file
#       if you want to update the values then do so from the settings.yaml file instead
service: ${self:custom.settings.awsRegionShortName}-${self:custom.settings.solutionName}-machine-images

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  region: ${self:custom.settings.awsRegion}
  profile: ${self:custom.settings.awsProfile}

custom:
  default.aws.profile: '' # Keep default profile to use as empty string to force people to specify profile or use env
  settings: ${file(./config/settings/.settings.js):merged}

plugins:
  - '@amzn/serverless-packer'
